
### get all products
GET http://localhost:4000/products


### add new product 
POST http://localhost:4000/products
Content-Type: application/json

{
  "title":"Cheese burger",
  "description":"hambuger with extra cheese",
  "price":4.99,
  "image":"chesseborger-image.png",
  "category":"pizzas"  
}

### get all products by category
GET http://localhost:4000/products/humburger

### get product by id
GET http://localhost:4000/products/product/60351ea4a21d68039d2250cc

###delete product by id
DELETE http://localhost:4000/products/60351ea4a21d68039d2250cc